#!/usr/bin/env bash
# displays bad luck in China, Japan and italy at 4, 9, 17 respectively 

i=1
while [ $i -le 20 ]
do
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	echo "$i"
	((i=i+1))
done